from building import *

cwd = GetCurrentDir()
src = Glob('spi_port.c')
inc = [cwd]

if GetDepend(['SSUD_BACKLIGHT_SWITCH']) or GetDepend(['SSUD_BACKLIGHT_PWM']):
    src += ['backlight_port.c']

group = DefineGroup('ui_drivers', src, depend = [''], CPPPATH = inc)

Return('group')
